import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.jsx',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Inter', ...defaultTheme.fontFamily.sans],
            },
            colors: {
                'on-secondary-fixed': '#251a00',
                'surface-container': '#e5eeff',
                'tertiary-fixed-dim': '#4edea3',
                'surface-dim': '#cbdbf5',
                background: '#f8f9ff',
                'on-primary-fixed-variant': '#00504d',
                'on-surface': '#0b1c30',
                'on-tertiary-fixed-variant': '#005236',
                'on-secondary': '#ffffff',
                'surface-container-highest': '#d3e4fe',
                'on-primary-container': '#d0fffb',
                'primary-fixed': '#94f3ed',
                'on-tertiary-fixed': '#002113',
                'tertiary-fixed': '#6ffbbe',
                'on-tertiary': '#ffffff',
                'surface-container-high': '#dce9ff',
                'on-error-container': '#93000a',
                outline: '#6e7978',
                'on-secondary-container': '#6f5400',
                'on-tertiary-container': '#daffe8',
                surface: '#f8f9ff',
                'surface-container-low': '#eff4ff',
                'primary-fixed-dim': '#78d6d1',
                'secondary-fixed-dim': '#f5bf23',
                'surface-container-lowest': '#ffffff',
                'tertiary-container': '#008158',
                'on-error': '#ffffff',
                'on-surface-variant': '#3e4948',
                primary: '#006360',
                error: '#ba1a1a',
                secondary: '#775a00',
                'secondary-fixed': '#ffdf98',
                'inverse-on-surface': '#eaf1ff',
                'primary-container': '#007e7a',
                'on-secondary-fixed-variant': '#5a4300',
                'inverse-surface': '#213145',
                'on-background': '#0b1c30',
                'surface-tint': '#006a66',
                'outline-variant': '#bdc9c7',
                'surface-variant': '#d3e4fe',
                'secondary-container': '#fec72d',
                'surface-bright': '#f8f9ff',
                tertiary: '#006545',
                'on-primary-fixed': '#00201f',
                'inverse-primary': '#78d6d1',
                'error-container': '#ffdad6',
                'on-primary': '#ffffff',
            },
            borderRadius: {
                DEFAULT: '0.25rem',
                lg: '0.5rem',
                xl: '0.75rem',
                full: '9999px',
            },
            spacing: {
                base: '4px',
                'stack-sm': '8px',
                'table-cell-x': '16px',
                gutter: '16px',
                'container-padding': '24px',
                'table-cell-y': '12px',
                'stack-md': '16px',
            },
            fontSize: {
                'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
                'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
                'title-sm': ['18px', { lineHeight: '28px', fontWeight: '600' }],
                'data-tabular': ['13px', { lineHeight: '16px', fontWeight: '500' }],
                'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
                'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
                'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
            },
        },
    },

    plugins: [forms],
};
